// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hupeyekrlkfgfwdmxjzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1cGV5ZWtybGtmZ2Z3ZG14anpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTY1NDgsImV4cCI6MjA1OTk3MjU0OH0.Vmld-xkYvnVYbEsKwWMC_G6s1dYvh03oXZuYORUFl40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);